---
- name: Check if PuTTY is installed
  win_reg_stat:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\Putty_is1
  register: putty_installed
  ignore_errors: yes

- name: Uninstall PuTTY if installed
  win_package:
    name: PuTTY release name or Product ID
    state: absent
  when: putty_installed.exists == true  # Only run if PuTTY is installed
