---
- name: Check if PuTTY is installed
  win_reg_stat:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\Putty_is1
  register: putty_installed
  ignore_errors: yes

- name: Uninstall PuTTY if installed
  win_command: msiexec /x "{2417E5FE-8DB8-401D-BD4E-2842D15202F7}" /qn
  when: putty_installed.exists == true  # Only run if PuTTY is installed
