---
- name: Check if PuTTY is installed
  win_shell: Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -like "*PuTTY*"}
  register: putty_installed
  ignore_errors: yes

- name: Uninstall PuTTY if found
  win_shell: msiexec /x {{ item.Id }} /qn
  loop: "{{ putty_installed.stdout | from_json }}"
  when: putty_installed.stdout != ""
